#!/bin/sh
hostip=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')
port=7890
socks_port=7890

if [ -n $2 ]
then
    hostip=$2
fi

PROXY_HTTP="http://${hostip}:${port}"
PROXY_SOCKS5="http://${hostip}:${socks_port}"

set_proxy(){
    export http_proxy="${PROXY_HTTP}"
    export https_proxy="${PROXY_HTTP}"
    export all_proxy="${PROXY_SOCKS5}"
}

unset_proxy(){
    unset http_proxy
    unset https_proxy
    unset all_proxy
}

test_setting(){
    echo "Host ip:" ${hostip}
    echo "Current proxy:" $https_proxy
}


if [ "$1" = "set" ]
then
    set_proxy

elif [ "$1" = "unset" ]
then
    unset_proxy

elif [ "$1" = "test" ]
then
    test_setting
else
    echo "Unsupported arguments."
fi

