#!/bin/sh

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Bibata-Modern-Classic

# Set a cursor size
export XCURSOR_SIZE=24

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland

export GDK_SCALE=2

if [ -x /usr/bin/Hyprland ]; then
    exec Hyprland
fi

if [ -x /usr/bin/sway ]; then
    exec sway
fi
