
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

monitor = HDMI-A-2, 1920x1080@60.00, 0x0, 1.25
monitor = DP-2, 3840x2160@160.00, 0x0, 2, bitdepth, 10
# monitor = ,preferred,auto,1,mirror,HDMI-A-1

